// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi_Project_Football.Data;

namespace WebApi_Project_Football.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi_Project_Football.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Russia"
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "England"
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "France"
                        });
                });

            modelBuilder.Entity("WebApi_Project_Football.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            LeagueName = "Russian Premier League"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            LeagueName = "FNL"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            LeagueName = "England Premier League"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            LeagueName = "English Football League Championship"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            LeagueName = "League One"
                        });
                });

            modelBuilder.Entity("WebApi_Project_Football.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatisticId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("StatisticId")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 27,
                            CountryId = 1,
                            FirstName = "Georgiy",
                            LastName = "Djikia",
                            Position = "Defender",
                            StatisticId = 3,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 26,
                            CountryId = 1,
                            FirstName = "Alexander",
                            LastName = "Golovin",
                            Position = "Midfielder",
                            StatisticId = 1,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 3,
                            Age = 23,
                            CountryId = 2,
                            FirstName = "Eddie",
                            LastName = "Nketiah",
                            Position = "Forward",
                            StatisticId = 2,
                            TeamId = 4
                        });
                });

            modelBuilder.Entity("WebApi_Project_Football.Models.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int?>("CleanSheets")
                        .HasColumnType("int");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("RedCards")
                        .HasColumnType("int");

                    b.Property<int>("YellowCards")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Statistics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Assists = 5,
                            GamesPlayed = 30,
                            Goals = 5,
                            MinutesPlayed = 2315,
                            RedCards = 1,
                            YellowCards = 5
                        },
                        new
                        {
                            Id = 2,
                            Assists = 0,
                            GamesPlayed = 12,
                            Goals = 9,
                            MinutesPlayed = 765,
                            RedCards = 0,
                            YellowCards = 3
                        },
                        new
                        {
                            Id = 3,
                            Assists = 1,
                            GamesPlayed = 21,
                            Goals = 1,
                            MinutesPlayed = 1540,
                            RedCards = 0,
                            YellowCards = 1
                        });
                });

            modelBuilder.Entity("WebApi_Project_Football.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeagueId = 1,
                            TeamName = "Spartak Moscow"
                        },
                        new
                        {
                            Id = 2,
                            LeagueId = 1,
                            TeamName = "Dinamo Moscow"
                        },
                        new
                        {
                            Id = 3,
                            LeagueId = 2,
                            TeamName = "Rubin Kazan"
                        },
                        new
                        {
                            Id = 4,
                            LeagueId = 3,
                            TeamName = "Arsenal"
                        },
                        new
                        {
                            Id = 5,
                            LeagueId = 4,
                            TeamName = "Watford"
                        },
                        new
                        {
                            Id = 6,
                            LeagueId = 5,
                            TeamName = "Monaco"
                        });
                });

            modelBuilder.Entity("WebApi_Project_Football.Models.League", b =>
                {
                    b.HasOne("WebApi_Project_Football.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WebApi_Project_Football.Models.Player", b =>
                {
                    b.HasOne("WebApi_Project_Football.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi_Project_Football.Models.Statistic", "Statistic")
                        .WithOne("Player")
                        .HasForeignKey("WebApi_Project_Football.Models.Player", "StatisticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi_Project_Football.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Statistic");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WebApi_Project_Football.Models.Team", b =>
                {
                    b.HasOne("WebApi_Project_Football.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("WebApi_Project_Football.Models.League", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("WebApi_Project_Football.Models.Statistic", b =>
                {
                    b.Navigation("Player");
                });

            modelBuilder.Entity("WebApi_Project_Football.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
